service: GraphCool2
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  stage: development
functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphiql
          method: get

  api:
    handler: api/frontcontroller.handler
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true